# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_auto_20161023_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_type', models.CharField(choices=[('parent', 'Parent'), ('sibling', 'Sibling'), ('child', 'Child'), ('step_parent', 'Step parent'), ('step_sibling', 'Step sibling'), ('step_child', 'Step child'), ('marriage', 'Marriage'), ('divorce', 'Divorce')], max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='inv.Person')),
                ('rel_persons', models.ManyToManyField(related_name='relations_from', to='inv.Person')),
            ],
        ),
    ]
