# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_personrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_type', models.CharField(choices=[('parent', 'Parent'), ('sibling', 'Sibling'), ('child', 'Child'), ('step_parent', 'Step parent'), ('step_sibling', 'Step sibling'), ('step_child', 'Step child'), ('marriage', 'Marriage'), ('divorce', 'Divorce')], max_length=20)),
                ('rel_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='personrelation',
            name='rel_persons',
        ),
        migrations.RemoveField(
            model_name='personrelation',
            name='rel_type',
        ),
        migrations.AddField(
            model_name='relation',
            name='related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.PersonRelation'),
        ),
        migrations.AddField(
            model_name='personrelation',
            name='rel',
            field=models.ManyToManyField(through='inv.Relation', to='inv.Person'),
        ),
    ]
