# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_auto_20161030_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personrelation',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personrelation',
            name='rel',
        ),
        migrations.AddField(
            model_name='person',
            name='relations',
            field=models.ManyToManyField(through='inv.Relation', to='inv.Person'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='rel_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_from', to='inv.Person'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_to', to='inv.Person'),
        ),
        migrations.DeleteModel(
            name='PersonRelation',
        ),
    ]
